package com.myspace.rhdm7_keralty;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Paciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cedula")
	private java.lang.String cedula;
	@org.kie.api.definition.type.Label("Edad")
	private java.lang.Integer edad;
	@org.kie.api.definition.type.Label("Genero")
	private java.lang.String genero;
	@org.kie.api.definition.type.Label("Codigo Acantosis")
	private java.lang.String codAcantosis;
	@org.kie.api.definition.type.Label("Codigo Diabetes Gestacional")
	private java.util.List<java.lang.String> codDiabetesGestacional;
	@org.kie.api.definition.type.Label("Codigo Enfermedad Cardiovascular")
	private java.util.List<java.lang.String> codCardiovascular;
	@org.kie.api.definition.type.Label("Codigo Evento Cerebro Vascular")
	private java.util.List<java.lang.String> codEcv;
	@org.kie.api.definition.type.Label("Codigo Hipertension Arterial")
	private java.util.List<java.lang.String> codHta;
	@org.kie.api.definition.type.Label("Codigo Falla Cardiaca")
	private java.util.List<java.lang.String> codFallaCardiaca;
	@org.kie.api.definition.type.Label("Codigo Ovario Poliquistico")
	private java.lang.String codOvarioPoliquistico;
	@org.kie.api.definition.type.Label("Actividad Fisica")
	private java.lang.Boolean actividadFisica;
	@org.kie.api.definition.type.Label("Estado Examen Glucosa en Suero")
	private java.lang.Boolean glucosaEnSuero;
	@org.kie.api.definition.type.Label("Historial de Glucosa Alta")
	private java.lang.Boolean histGlucosaAlta;
	@org.kie.api.definition.type.Label("Alimentacion Saludable")
	private java.lang.Boolean alimentacionSaludable;
	@org.kie.api.definition.type.Label("Contraindicaciones Dpp4")
	private java.lang.Boolean contraindicacionesDpp4;
	@org.kie.api.definition.type.Label("ContraindicacionesSglt2")
	private java.lang.Boolean contraindicacionesSglt2;
	@org.kie.api.definition.type.Label("Contraindicaciones Metformina")
	private java.lang.Boolean contraindicacionesMetformina;
	@org.kie.api.definition.type.Label("Herencia Diabetes Grado Uno")
	private java.lang.Boolean herenciaDiabetesGradoUno;
	@org.kie.api.definition.type.Label("Herencia Diabetes Grado Dos")
	private java.lang.Boolean herenciaDiabetesGradoDos;
	@org.kie.api.definition.type.Label("Hijos con mas de cuatro Kg al nacer")
	private java.lang.Boolean hijosMasCuatroKgAlNacer;
	@org.kie.api.definition.type.Label("Medicamentos Hipertension")
	private java.lang.Boolean medicamentosHipertension;
	@org.kie.api.definition.type.Label("Tratamiento con Medicamento")
	private java.lang.Boolean tratamientoConMedicamento;
	@org.kie.api.definition.type.Label("Sedentarismo")
	private java.lang.Boolean sedentarismo;
	@org.kie.api.definition.type.Label("Tiene Comorbilidades")
	private java.lang.Boolean tieneComorbilidades;
	@org.kie.api.definition.type.Label("Tiene Evento Cerebro Vascular")
	private java.lang.Boolean tieneEcv;
	@org.kie.api.definition.type.Label("Tiene Falla Cardiaca")
	private java.lang.Boolean tieneFallaCardiaca;
	@org.kie.api.definition.type.Label("Tiene HTA")
	private java.lang.Boolean tieneHta;
	@org.kie.api.definition.type.Label("Tiene Enfermedades Cardiovasculares")
	private java.lang.Boolean tieneCardiovasculares;
	@org.kie.api.definition.type.Label("Tiene Diabetes Gestacional")
	private java.lang.Boolean tieneDiabetesGestacional;
    @org.kie.api.definition.type.Label(value = "Segunda Prueba Diabetes")
	private java.lang.Boolean segundaPrueba;
	@org.kie.api.definition.type.Label("Valor Findrisk")
	private java.lang.Integer findrisk;
	@org.kie.api.definition.type.Label("Valor Glicemia")
	private java.lang.Double glicemia;
	@org.kie.api.definition.type.Label("Valor HBA1C")
	private java.lang.Double hba1c;
	@org.kie.api.definition.type.Label("Valor HDL")
	private java.lang.Double hdl;
	@org.kie.api.definition.type.Label("Valor Hipertension Diastolico")
	private java.lang.Double hipertensionDiastolico;
	@org.kie.api.definition.type.Label("Valor Hipertension Sistolico")
	private java.lang.Double hipertensionSistolico;
	@org.kie.api.definition.type.Label("Valor Indice de Masa Corporal")
	private java.lang.Double imc;
	@org.kie.api.definition.type.Label("Valor Perimetro Abdominal")
	private java.lang.Double perimetroAbdominal;
	@org.kie.api.definition.type.Label("Valor Postprandial")
	private java.lang.Double postprandial;
	@org.kie.api.definition.type.Label("Valor Preprandial")
	private java.lang.Double preprandial;
	@org.kie.api.definition.type.Label("Valor RAC")
	private java.lang.Double rac;
	@org.kie.api.definition.type.Label("Valor Trigliceridos")
	private java.lang.Double trigliceridos;
	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;

	public Paciente() {
	}

	public java.lang.String getCodAcantosis() {
		return this.codAcantosis;
	}

	public void setCodAcantosis(java.lang.String codAcantosis) {
		this.codAcantosis = codAcantosis;
	}

	public java.lang.Boolean getActividadFisica() {
		return this.actividadFisica;
	}

	public void setActividadFisica(java.lang.Boolean actividadFisica) {
		this.actividadFisica = actividadFisica;
	}

	public java.lang.Boolean getAlimentacionSaludable() {
		return this.alimentacionSaludable;
	}

	public void setAlimentacionSaludable(java.lang.Boolean alimentacionSaludable) {
		this.alimentacionSaludable = alimentacionSaludable;
	}

	public java.util.List<java.lang.String> getCodDiabetesGestacional() {
		return this.codDiabetesGestacional;
	}

	public void setCodDiabetesGestacional(
			java.util.List<java.lang.String> codDiabetesGestacional) {
		this.codDiabetesGestacional = codDiabetesGestacional;
	}

	public java.util.List<java.lang.String> getCodCardiovascular() {
		return this.codCardiovascular;
	}

	public void setCodCardiovascular(
			java.util.List<java.lang.String> codCardiovascular) {
		this.codCardiovascular = codCardiovascular;
	}

	public java.util.List<java.lang.String> getCodEcv() {
		return this.codEcv;
	}

	public void setCodEcv(java.util.List<java.lang.String> codEcv) {
		this.codEcv = codEcv;
	}

	public java.util.List<java.lang.String> getCodHta() {
		return this.codHta;
	}

	public void setCodHta(java.util.List<java.lang.String> codHta) {
		this.codHta = codHta;
	}

	public java.util.List<java.lang.String> getCodFallaCardiaca() {
		return this.codFallaCardiaca;
	}

	public void setCodFallaCardiaca(
			java.util.List<java.lang.String> codFallaCardiaca) {
		this.codFallaCardiaca = codFallaCardiaca;
	}

	public java.lang.Boolean getContraindicacionesDpp4() {
		return this.contraindicacionesDpp4;
	}

	public void setContraindicacionesDpp4(
			java.lang.Boolean contraindicacionesDpp4) {
		this.contraindicacionesDpp4 = contraindicacionesDpp4;
	}

	public java.lang.Boolean getContraindicacionesSglt2() {
		return this.contraindicacionesSglt2;
	}

	public void setContraindicacionesSglt2(
			java.lang.Boolean contraindicacionesSglt2) {
		this.contraindicacionesSglt2 = contraindicacionesSglt2;
	}

	public java.lang.Boolean getContraindicacionesMetformina() {
		return this.contraindicacionesMetformina;
	}

	public void setContraindicacionesMetformina(
			java.lang.Boolean contraindicacionesMetformina) {
		this.contraindicacionesMetformina = contraindicacionesMetformina;
	}

	public java.lang.Integer getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.Integer edad) {
		this.edad = edad;
	}

	public java.lang.Integer getFindrisk() {
		return this.findrisk;
	}

	public void setFindrisk(java.lang.Integer findrisk) {
		this.findrisk = findrisk;
	}

	public java.lang.String getGenero() {
		return this.genero;
	}

	public void setGenero(java.lang.String genero) {
		this.genero = genero;
	}

	public java.lang.Double getGlicemia() {
		return this.glicemia;
	}

	public void setGlicemia(java.lang.Double glicemia) {
		this.glicemia = glicemia;
	}

	public java.lang.Boolean getGlucosaEnSuero() {
		return this.glucosaEnSuero;
	}

	public void setGlucosaEnSuero(java.lang.Boolean glucosaEnSuero) {
		this.glucosaEnSuero = glucosaEnSuero;
	}

	public java.lang.Double getHba1c() {
		return this.hba1c;
	}

	public void setHba1c(java.lang.Double hba1c) {
		this.hba1c = hba1c;
	}

	public java.lang.Double getHdl() {
		return this.hdl;
	}

	public void setHdl(java.lang.Double hdl) {
		this.hdl = hdl;
	}

	public java.lang.Boolean getHerenciaDiabetesGradoUno() {
		return this.herenciaDiabetesGradoUno;
	}

	public void setHerenciaDiabetesGradoUno(
			java.lang.Boolean herenciaDiabetesGradoUno) {
		this.herenciaDiabetesGradoUno = herenciaDiabetesGradoUno;
	}

	public java.lang.Boolean getHerenciaDiabetesGradoDos() {
		return this.herenciaDiabetesGradoDos;
	}

	public void setHerenciaDiabetesGradoDos(
			java.lang.Boolean herenciaDiabetesGradoDos) {
		this.herenciaDiabetesGradoDos = herenciaDiabetesGradoDos;
	}

	public java.lang.Boolean getHijosMasCuatroKgAlNacer() {
		return this.hijosMasCuatroKgAlNacer;
	}

	public void setHijosMasCuatroKgAlNacer(
			java.lang.Boolean hijosMasCuatroKgAlNacer) {
		this.hijosMasCuatroKgAlNacer = hijosMasCuatroKgAlNacer;
	}

	public java.lang.Double getHipertensionDiastolico() {
		return this.hipertensionDiastolico;
	}

	public void setHipertensionDiastolico(
			java.lang.Double hipertensionDiastolico) {
		this.hipertensionDiastolico = hipertensionDiastolico;
	}

	public java.lang.Double getHipertensionSistolico() {
		return this.hipertensionSistolico;
	}

	public void setHipertensionSistolico(java.lang.Double hipertensionSistolico) {
		this.hipertensionSistolico = hipertensionSistolico;
	}

	public java.lang.Boolean getHistGlucosaAlta() {
		return this.histGlucosaAlta;
	}

	public void setHistGlucosaAlta(java.lang.Boolean histGlucosaAlta) {
		this.histGlucosaAlta = histGlucosaAlta;
	}

	public java.lang.Double getImc() {
		return this.imc;
	}

	public void setImc(java.lang.Double imc) {
		this.imc = imc;
	}

	public java.lang.Boolean getMedicamentosHipertension() {
		return this.medicamentosHipertension;
	}

	public void setMedicamentosHipertension(
			java.lang.Boolean medicamentosHipertension) {
		this.medicamentosHipertension = medicamentosHipertension;
	}

	public java.lang.String getCodOvarioPoliquistico() {
		return this.codOvarioPoliquistico;
	}

	public void setCodOvarioPoliquistico(java.lang.String codOvarioPoliquistico) {
		this.codOvarioPoliquistico = codOvarioPoliquistico;
	}

	public java.lang.Double getPerimetroAbdominal() {
		return this.perimetroAbdominal;
	}

	public void setPerimetroAbdominal(java.lang.Double perimetroAbdominal) {
		this.perimetroAbdominal = perimetroAbdominal;
	}

	public java.lang.Double getPostprandial() {
		return this.postprandial;
	}

	public void setPostprandial(java.lang.Double postprandial) {
		this.postprandial = postprandial;
	}

	public java.lang.Double getPreprandial() {
		return this.preprandial;
	}

	public void setPreprandial(java.lang.Double preprandial) {
		this.preprandial = preprandial;
	}

	public java.lang.Double getRac() {
		return this.rac;
	}

	public void setRac(java.lang.Double rac) {
		this.rac = rac;
	}

	public java.lang.Double getTrigliceridos() {
		return this.trigliceridos;
	}

	public void setTrigliceridos(java.lang.Double trigliceridos) {
		this.trigliceridos = trigliceridos;
	}

	public java.lang.Boolean getTratamientoConMedicamento() {
		return this.tratamientoConMedicamento;
	}

	public void setTratamientoConMedicamento(
			java.lang.Boolean tratamientoConMedicamento) {
		this.tratamientoConMedicamento = tratamientoConMedicamento;
	}

	public java.lang.Boolean getSedentarismo() {
		return this.sedentarismo;
	}

	public void setSedentarismo(java.lang.Boolean sedentarismo) {
		this.sedentarismo = sedentarismo;
	}

	public java.lang.Boolean getTieneComorbilidades() {
		return this.tieneComorbilidades;
	}

	public void setTieneComorbilidades(java.lang.Boolean tieneComorbilidades) {
		this.tieneComorbilidades = tieneComorbilidades;
	}

	public java.lang.Boolean getTieneEcv() {
		return this.tieneEcv;
	}

	public void setTieneEcv(java.lang.Boolean tieneEcv) {
		this.tieneEcv = tieneEcv;
	}

	public java.lang.Boolean getTieneFallaCardiaca() {
		return this.tieneFallaCardiaca;
	}

	public void setTieneFallaCardiaca(java.lang.Boolean tieneFallaCardiaca) {
		this.tieneFallaCardiaca = tieneFallaCardiaca;
	}

	public java.lang.Boolean getTieneHta() {
		return this.tieneHta;
	}

	public void setTieneHta(java.lang.Boolean tieneHta) {
		this.tieneHta = tieneHta;
	}

	public java.lang.Boolean getTieneCardiovasculares() {
		return this.tieneCardiovasculares;
	}

	public void setTieneCardiovasculares(java.lang.Boolean tieneCardiovasculares) {
		this.tieneCardiovasculares = tieneCardiovasculares;
	}

	public java.lang.Boolean getTieneDiabetesGestacional() {
		return this.tieneDiabetesGestacional;
	}

	public void setTieneDiabetesGestacional(
			java.lang.Boolean tieneDiabetesGestacional) {
		this.tieneDiabetesGestacional = tieneDiabetesGestacional;
	}
	
	public java.lang.Boolean getSegundaPrueba() {
		return this.segundaPrueba;
	}

	public void setSegundaPrueba(java.lang.Boolean segundaPrueba) {
		this.segundaPrueba = segundaPrueba;
	}

	public java.lang.String getCedula() {
		return this.cedula;
	}

	public void setCedula(java.lang.String cedula) {
		this.cedula = cedula;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public Paciente(java.lang.String codAcantosis,
			java.lang.Boolean actividadFisica,
			java.lang.Boolean alimentacionSaludable,
			java.util.List<java.lang.String> codDiabetesGestacional,
			java.util.List<java.lang.String> codCardiovascular,
			java.util.List<java.lang.String> codEcv,
			java.util.List<java.lang.String> codHta,
			java.util.List<java.lang.String> codFallaCardiaca,
			java.lang.Boolean contraindicacionesDpp4,
			java.lang.Boolean contraindicacionesSglt2,
			java.lang.Boolean contraindicacionesMetformina,
			java.lang.Integer edad, java.lang.Integer findrisk,
			java.lang.String genero, java.lang.Double glicemia,
			java.lang.Boolean glucosaEnSuero, java.lang.Double hba1c,
			java.lang.Double hdl, java.lang.Boolean herenciaDiabetesGradoUno,
			java.lang.Boolean herenciaDiabetesGradoDos,
			java.lang.Boolean hijosMasCuatroKgAlNacer,
			java.lang.Double hipertensionDiastolico,
			java.lang.Double hipertensionSistolico,
			java.lang.Boolean histGlucosaAlta, java.lang.Double imc,
			java.lang.Boolean medicamentosHipertension,
			java.lang.String codOvarioPoliquistico,
			java.lang.Double perimetroAbdominal, java.lang.Double postprandial,
			java.lang.Double preprandial, java.lang.Double rac,
			java.lang.Double trigliceridos,
			java.lang.Boolean tratamientoConMedicamento,
			java.lang.Boolean sedentarismo,
			java.lang.Boolean tieneComorbilidades,
			java.lang.Boolean tieneFallaCardiaca, java.lang.Boolean tieneHta,
			java.lang.String cedula, java.lang.String mensaje) {
		this.codAcantosis = codAcantosis;
		this.actividadFisica = actividadFisica;
		this.alimentacionSaludable = alimentacionSaludable;
		this.codDiabetesGestacional = codDiabetesGestacional;
		this.codCardiovascular = codCardiovascular;
		this.codEcv = codEcv;
		this.codHta = codHta;
		this.codFallaCardiaca = codFallaCardiaca;
		this.contraindicacionesDpp4 = contraindicacionesDpp4;
		this.contraindicacionesSglt2 = contraindicacionesSglt2;
		this.contraindicacionesMetformina = contraindicacionesMetformina;
		this.edad = edad;
		this.findrisk = findrisk;
		this.genero = genero;
		this.glicemia = glicemia;
		this.glucosaEnSuero = glucosaEnSuero;
		this.hba1c = hba1c;
		this.hdl = hdl;
		this.herenciaDiabetesGradoUno = herenciaDiabetesGradoUno;
		this.herenciaDiabetesGradoDos = herenciaDiabetesGradoDos;
		this.hijosMasCuatroKgAlNacer = hijosMasCuatroKgAlNacer;
		this.hipertensionDiastolico = hipertensionDiastolico;
		this.hipertensionSistolico = hipertensionSistolico;
		this.histGlucosaAlta = histGlucosaAlta;
		this.imc = imc;
		this.medicamentosHipertension = medicamentosHipertension;
		this.codOvarioPoliquistico = codOvarioPoliquistico;
		this.perimetroAbdominal = perimetroAbdominal;
		this.postprandial = postprandial;
		this.preprandial = preprandial;
		this.rac = rac;
		this.trigliceridos = trigliceridos;
		this.tratamientoConMedicamento = tratamientoConMedicamento;
		this.sedentarismo = sedentarismo;
		this.tieneComorbilidades = tieneComorbilidades;
		this.tieneFallaCardiaca = tieneFallaCardiaca;
		this.tieneHta = tieneHta;
		this.cedula = cedula;
		this.mensaje = mensaje;
	}

	public String toString() {
		return "Metodo toString " + this.tieneComorbilidades;
	}

	public Paciente(java.lang.String cedula, java.lang.Integer edad,
			java.lang.String genero, java.lang.String codAcantosis,
			java.util.List<java.lang.String> codDiabetesGestacional,
			java.util.List<java.lang.String> codCardiovascular,
			java.util.List<java.lang.String> codEcv,
			java.util.List<java.lang.String> codHta,
			java.util.List<java.lang.String> codFallaCardiaca,
			java.lang.String codOvarioPoliquistico,
			java.lang.Boolean actividadFisica,
			java.lang.Boolean glucosaEnSuero,
			java.lang.Boolean histGlucosaAlta,
			java.lang.Boolean alimentacionSaludable,
			java.lang.Boolean contraindicacionesDpp4,
			java.lang.Boolean contraindicacionesSglt2,
			java.lang.Boolean contraindicacionesMetformina,
			java.lang.Boolean herenciaDiabetesGradoUno,
			java.lang.Boolean herenciaDiabetesGradoDos,
			java.lang.Boolean hijosMasCuatroKgAlNacer,
			java.lang.Boolean medicamentosHipertension,
			java.lang.Boolean tratamientoConMedicamento,
			java.lang.Boolean sedentarismo,
			java.lang.Boolean tieneComorbilidades, java.lang.Boolean tieneEcv,
			java.lang.Boolean tieneFallaCardiaca, java.lang.Boolean tieneHta,
			java.lang.Boolean segundaPrueba,
			java.lang.Boolean tieneCardiovasculares,
			java.lang.Boolean tieneDiabetesGestacional,
			java.lang.Integer findrisk, java.lang.Double glicemia,
			java.lang.Double hba1c, java.lang.Double hdl,
			java.lang.Double hipertensionDiastolico,
			java.lang.Double hipertensionSistolico, java.lang.Double imc,
			java.lang.Double perimetroAbdominal, java.lang.Double postprandial,
			java.lang.Double preprandial, java.lang.Double rac,
			java.lang.Double trigliceridos, java.lang.String mensaje) {
		this.cedula = cedula;
		this.edad = edad;
		this.genero = genero;
		this.codAcantosis = codAcantosis;
		this.codDiabetesGestacional = codDiabetesGestacional;
		this.codCardiovascular = codCardiovascular;
		this.codEcv = codEcv;
		this.codHta = codHta;
		this.codFallaCardiaca = codFallaCardiaca;
		this.codOvarioPoliquistico = codOvarioPoliquistico;
		this.actividadFisica = actividadFisica;
		this.glucosaEnSuero = glucosaEnSuero;
		this.histGlucosaAlta = histGlucosaAlta;
		this.alimentacionSaludable = alimentacionSaludable;
		this.contraindicacionesDpp4 = contraindicacionesDpp4;
		this.contraindicacionesSglt2 = contraindicacionesSglt2;
		this.contraindicacionesMetformina = contraindicacionesMetformina;
		this.herenciaDiabetesGradoUno = herenciaDiabetesGradoUno;
		this.herenciaDiabetesGradoDos = herenciaDiabetesGradoDos;
		this.hijosMasCuatroKgAlNacer = hijosMasCuatroKgAlNacer;
		this.medicamentosHipertension = medicamentosHipertension;
		this.tratamientoConMedicamento = tratamientoConMedicamento;
		this.sedentarismo = sedentarismo;
		this.tieneComorbilidades = tieneComorbilidades;
		this.tieneEcv = tieneEcv;
		this.tieneFallaCardiaca = tieneFallaCardiaca;
		this.tieneHta = tieneHta;
		this.tieneCardiovasculares = tieneCardiovasculares;
		this.tieneDiabetesGestacional = tieneDiabetesGestacional;
		this.segundaPrueba = segundaPrueba;
		this.findrisk = findrisk;
		this.glicemia = glicemia;
		this.hba1c = hba1c;
		this.hdl = hdl;
		this.hipertensionDiastolico = hipertensionDiastolico;
		this.hipertensionSistolico = hipertensionSistolico;
		this.imc = imc;
		this.perimetroAbdominal = perimetroAbdominal;
		this.postprandial = postprandial;
		this.preprandial = preprandial;
		this.rac = rac;
		this.trigliceridos = trigliceridos;
		this.mensaje = mensaje;
	}

}